name: hello-world

on: push

jobs: 
  
  my-hello-world-job:
    
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
